# NumPy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

In [96]:
import numpy as np

## 创建 Array

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the `rank` of the array; the `shape` of an array is a tuple of integers giving the size of the array along each dimension.

### Converting Python sequences to NumPy Arrays

- a list of numbers will create a 1D array,  
- a list of lists will create a 2D array,  
- further nested lists will create higher-dimensional arrays. In general, any array object is called an ndarray in NumPy.

In [97]:
a1D = np.array([1, 2, 3, 4])

In [98]:
a2D = np.array([[1, 2], [3, 4]])

In [99]:
a3D = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])

### Data types

| 名称       | 描述                                                         |  
| :--------- | :----------------------------------------------------------- |  
| bool_      | 布尔型数据类型（True 或者 False）                            |  
| int_       | 默认的整数类型（类似于 C 语言中的 long，int32 或 int64）     |  
| intc       | 与 C 的 int 类型一样，一般是 int32 或 int 64                 |  
| intp       | 用于索引的整数类型（类似于 C 的 ssize_t，一般情况下仍然是 int32 或 int64） |  
| int8       | 字节（-128 to 127）                                          |  
| int16      | 整数（-32768 to 32767）                                      |  
| int32      | 整数（-2147483648 to 2147483647）                            |  
| int64      | 整数（-9223372036854775808 to 9223372036854775807）          |  
| uint8      | 无符号整数（0 to 255）                                       |  
| uint16     | 无符号整数（0 to 65535）                                     |  
| uint32     | 无符号整数（0 to 4294967295）                                |  
| uint64     | 无符号整数（0 to 18446744073709551615）                      |  
| float_     | float64 类型的简写                                           |  
| float16    | 半精度浮点数，包括：1 个符号位，5 个指数位，10 个尾数位      |  
| float32    | 单精度浮点数，包括：1 个符号位，8 个指数位，23 个尾数位      |  
| float64    | 双精度浮点数，包括：1 个符号位，11 个指数位，52 个尾数位     |  
| complex_   | complex128 类型的简写，即 128 位复数                         |  
| complex64  | 复数，表示双 32 位浮点数（实数部分和虚数部分）               |  
| complex128 | 复数，表示双 64 位浮点数（实数部分和虚数部分）               |  

numpy 的数值类型实际上是 dtype 对象的实例，并对应唯一的字符，包括 np.bool_，np.int32，np.float32，等等。

In [100]:
np.array([1, 2, 3, 4], dtype=np.int64)

array([1, 2, 3, 4])

In [101]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

### Intrinsic NumPy array creation functions

NumPy has over 40 built-in functions for creating arrays as laid out in the Array creation routines. These functions can be split into roughly three categories, based on the dimension of the array they create:  

- 1D arrays  

- 2D arrays  

- ndarrays

#### 1D array creation functions

`numpy.arange` creates arrays with regularly incrementing values. Check the documentation for complete information and examples. A few examples are shown:

In [102]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [104]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

`numpy.linspace` will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. For example:

In [105]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

#### 2D array creation functions

`np.eye(n, m)` defines a 2D identity matrix. The elements where i=j (row index and column index are equal) are 1 and the rest are 0, as such:

In [106]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [107]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

`numpy.diag` can define either a square 2D array with given values along the diagonal or if given a 2D array returns a 1D array that is only the diagonal elements. The two array creation functions can be helpful while doing linear algebra, as such:

In [108]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [109]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [110]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

#### general ndarray creation functions

`numpy.zeros` will create an array filled with 0 values with the specified shape. The default dtype is float64:

In [111]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [112]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

`numpy.ones` will create an array filled with 1 values. It is identical to zeros in all other respects as such:

In [113]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [114]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### Replicating, joining, or mutating existing arrays

Once you have created arrays, you can replicate, join, or mutate those existing arrays to create new arrays. When you assign an array or its elements to a new variable, you have to explicitly `numpy.copy` the array, otherwise the variable is a view into the original array. Consider the following example:

In [115]:
a = np.array([1, 2, 3, 4, 5, 6])

b = a[:2]
b += 1

print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In this example, you did not create a new array. You created a variable, `b` that viewed the first 2 elements of `a`. When you added 1 to `b` you would get the same result by adding 1 to `a[:2]`. If you want to create a new array, use the `numpy.copy` array creation routine as such:

In [116]:
a = np.array([1, 2, 3, 4])

b = a[:2].copy()
b += 1

print('a = ', a, 'b = ', b)

a =  [1 2 3 4] b =  [2 3]


There are a number of routines to join existing arrays e.g. [`numpy.vstack`](https://numpy.org/devdocs/reference/generated/numpy.vstack.html#numpy.vstack), [`numpy.hstack`](https://numpy.org/devdocs/reference/generated/numpy.hstack.html#numpy.hstack), and [`numpy.block`](https://numpy.org/devdocs/reference/generated/numpy.block.html#numpy.block). Here is an example of joining four 2-by-2 arrays into a 4-by-4 array using `block`:

In [117]:
A = np.ones((2, 2))
B = np.eye(2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))

np.block([[A, B],
          [C, D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

### Reading arrays from disk

In [118]:
# np.loadtxt('files/airtravel.csv', delimiter = ',',) 

## NumPy Array Attributes

First let's discuss some useful array attributes.  
We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array.  
We'll use NumPy's random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [119]:
x1 = np.arange(6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [120]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Another useful attribute is the ``dtype``, the data type of the array:

In [121]:
print("dtype:", x3.dtype)

dtype: int64


Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [122]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.

## 操作Array

### Array Indexing: Accessing Single Elements

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.  
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [123]:
x1

array([0, 1, 2, 3, 4, 5])

In [124]:
x1[0]

0

In [125]:
x1[4]

4

To index from the end of the array, you can use negative indices:

In [126]:
x1[-1]

5

In [127]:
x1[-2]

4

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [128]:
x2

array([[9, 0, 5, 4],
       [6, 0, 1, 5],
       [0, 1, 2, 6]])

In [129]:
x2[0, 0]

9

In [130]:
x2[2, 0]

0

In [131]:
x2[2, -1]

6

Values can also be modified using any of the above index notation:

In [132]:
x2[0, 0] = 12
x2

array([[12,  0,  5,  4],
       [ 6,  0,  1,  5],
       [ 0,  1,  2,  6]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.  
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [133]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 1, 2, 3, 4, 5])

### Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.  
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:  
```python  
x[start:stop:step]  
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.  
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

#### One-dimensional subarrays

In [134]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [136]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [137]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [138]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [139]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

A potentially confusing case is when the ``step`` value is negative.  
In this case, the defaults for ``start`` and ``stop`` are swapped.  
This becomes a convenient way to reverse an array:  


In [140]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [141]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

#### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.  
For example:  


In [142]:
x2

array([[12,  0,  5,  4],
       [ 6,  0,  1,  5],
       [ 0,  1,  2,  6]])

In [143]:
x2[:2, :3]  # two rows, three columns

array([[12,  0,  5],
       [ 6,  0,  1]])

In [144]:
x2[:3, ::2]  # all rows, every other column

array([[12,  5],
       [ 6,  1],
       [ 0,  2]])

Finally, subarray dimensions can even be reversed together:

In [145]:
x2[::-1, ::-1]

array([[ 6,  2,  1,  0],
       [ 5,  1,  0,  6],
       [ 4,  5,  0, 12]])

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.  
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):  


In [146]:
print(x2[:, 0])  # first column of x2

[12  6  0]


In [147]:
print(x2[0, :])  # first row of x2

[12  0  5  4]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [148]:
print(x2[0])  # equivalent to x2[0, :]

[12  0  5  4]


#### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.  
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.  
Consider our two-dimensional array from before:  


In [149]:
print(x2)

[[12  0  5  4]
 [ 6  0  1  5]
 [ 0  1  2  6]]


Let's extract a $2 \times 2$ subarray from this:

In [150]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  0]
 [ 6  0]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [151]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  0]
 [ 6  0]]


In [152]:
print(x2)

[[99  0  5  4]
 [ 6  0  1  5]
 [ 0  1  2  6]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

#### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:  


In [153]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  0]
 [ 6  0]]


If we now modify this subarray, the original array is not touched:

In [154]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  0]
 [ 6  0]]


In [155]:
print(x2)

[[99  0  5  4]
 [ 6  0  1  5]
 [ 0  1  2  6]]


### Reshaping of Arrays

Another useful type of operation is reshaping of arrays.  
The most flexible way of doing this is with the ``reshape`` method.  
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:  


In [156]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array.  
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.  
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:  


In [157]:
x = np.array([1, 2, 3])

In [158]:
# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [159]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [160]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [161]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### Math operations

In [162]:
a = np.arange(5)

b = np.array([3, 4, 5, 1, 9])

In [163]:
a ** b

array([     0,      1,     32,      3, 262144])

In [164]:
a + b

array([ 3,  5,  7,  4, 13])

In [165]:
a / b

array([0.        , 0.25      , 0.4       , 3.        , 0.44444444])

https://numpy.org/doc/stable/reference/routines.math.html

**Trigonometric functions**  

| [`sin`](https://numpy.org/doc/stable/reference/generated/numpy.sin.html#numpy.sin)(x, /[, out, where, casting, order, …]) | Trigonometric sine, element-wise.                            |  
| ------------------------------------------------------------ | ------------------------------------------------------------ |  
| [`cos`](https://numpy.org/doc/stable/reference/generated/numpy.cos.html#numpy.cos)(x, /[, out, where, casting, order, …]) | Cosine element-wise.                                         |  
| [`tan`](https://numpy.org/doc/stable/reference/generated/numpy.tan.html#numpy.tan)(x, /[, out, where, casting, order, …]) | Compute tangent element-wise.                                |  
| [`arcsin`](https://numpy.org/doc/stable/reference/generated/numpy.arcsin.html#numpy.arcsin)(x, /[, out, where, casting, order, …]) | Inverse sine, element-wise.                                  |  
| [`arccos`](https://numpy.org/doc/stable/reference/generated/numpy.arccos.html#numpy.arccos)(x, /[, out, where, casting, order, …]) | Trigonometric inverse cosine, element-wise.                  |  
| [`arctan`](https://numpy.org/doc/stable/reference/generated/numpy.arctan.html#numpy.arctan)(x, /[, out, where, casting, order, …]) | Trigonometric inverse tangent, element-wise.                 |  
| [`hypot`](https://numpy.org/doc/stable/reference/generated/numpy.hypot.html#numpy.hypot)(x1, x2, /[, out, where, casting, …]) | Given the “legs” of a right triangle, return its hypotenuse. |  
| [`arctan2`](https://numpy.org/doc/stable/reference/generated/numpy.arctan2.html#numpy.arctan2)(x1, x2, /[, out, where, casting, …]) | Element-wise arc tangent of `x1/x2` choosing the quadrant correctly. |  
| [`degrees`](https://numpy.org/doc/stable/reference/generated/numpy.degrees.html#numpy.degrees)(x, /[, out, where, casting, order, …]) | Convert angles from radians to degrees.                      |  
| [`radians`](https://numpy.org/doc/stable/reference/generated/numpy.radians.html#numpy.radians)(x, /[, out, where, casting, order, …]) | Convert angles from degrees to radians.                      |  
| [`unwrap`](https://numpy.org/doc/stable/reference/generated/numpy.unwrap.html#numpy.unwrap)(p[, discont, axis, period]) | Unwrap by taking the complement of large deltas with respect to the period. |  
| [`deg2rad`](https://numpy.org/doc/stable/reference/generated/numpy.deg2rad.html#numpy.deg2rad)(x, /[, out, where, casting, order, …]) | Convert angles from degrees to radians.                      |  
| [`rad2deg`](https://numpy.org/doc/stable/reference/generated/numpy.rad2deg.html#numpy.rad2deg)(x, /[, out, where, casting, order, …]) | Convert angles from radians to degrees.                      |  

**Hyperbolic functions**  

| [`sinh`](https://numpy.org/doc/stable/reference/generated/numpy.sinh.html#numpy.sinh)(x, /[, out, where, casting, order, …]) | Hyperbolic sine, element-wise.           |  
| ------------------------------------------------------------ | ---------------------------------------- |  
| [`cosh`](https://numpy.org/doc/stable/reference/generated/numpy.cosh.html#numpy.cosh)(x, /[, out, where, casting, order, …]) | Hyperbolic cosine, element-wise.         |  
| [`tanh`](https://numpy.org/doc/stable/reference/generated/numpy.tanh.html#numpy.tanh)(x, /[, out, where, casting, order, …]) | Compute hyperbolic tangent element-wise. |  
| [`arcsinh`](https://numpy.org/doc/stable/reference/generated/numpy.arcsinh.html#numpy.arcsinh)(x, /[, out, where, casting, order, …]) | Inverse hyperbolic sine element-wise.    |  
| [`arccosh`](https://numpy.org/doc/stable/reference/generated/numpy.arccosh.html#numpy.arccosh)(x, /[, out, where, casting, order, …]) | Inverse hyperbolic cosine, element-wise. |  
| [`arctanh`](https://numpy.org/doc/stable/reference/generated/numpy.arctanh.html#numpy.arctanh)(x, /[, out, where, casting, order, …]) | Inverse hyperbolic tangent element-wise. |  

**Rounding**  

| [`around`](https://numpy.org/doc/stable/reference/generated/numpy.around.html#numpy.around)(a[, decimals, out]) | Evenly round to the given number of decimals.          |  
| ------------------------------------------------------------ | ------------------------------------------------------ |  
| [`round_`](https://numpy.org/doc/stable/reference/generated/numpy.round_.html#numpy.round_)(a[, decimals, out]) | Round an array to the given number of decimals.        |  
| [`rint`](https://numpy.org/doc/stable/reference/generated/numpy.rint.html#numpy.rint)(x, /[, out, where, casting, order, …]) | Round elements of the array to the nearest integer.    |  
| [`fix`](https://numpy.org/doc/stable/reference/generated/numpy.fix.html#numpy.fix)(x[, out]) | Round to nearest integer towards zero.                 |  
| [`floor`](https://numpy.org/doc/stable/reference/generated/numpy.floor.html#numpy.floor)(x, /[, out, where, casting, order, …]) | Return the floor of the input, element-wise.           |  
| [`ceil`](https://numpy.org/doc/stable/reference/generated/numpy.ceil.html#numpy.ceil)(x, /[, out, where, casting, order, …]) | Return the ceiling of the input, element-wise.         |  
| [`trunc`](https://numpy.org/doc/stable/reference/generated/numpy.trunc.html#numpy.trunc)(x, /[, out, where, casting, order, …]) | Return the truncated value of the input, element-wise. |  

**Sums, products, differences**  

| [`prod`](https://numpy.org/doc/stable/reference/generated/numpy.prod.html#numpy.prod)(a[, axis, dtype, out, keepdims, …]) | Return the product of array elements over a given axis.      |  
| ------------------------------------------------------------ | ------------------------------------------------------------ |  
| [`sum`](https://numpy.org/doc/stable/reference/generated/numpy.sum.html#numpy.sum)(a[, axis, dtype, out, keepdims, …]) | Sum of array elements over a given axis.                     |  
| [`nanprod`](https://numpy.org/doc/stable/reference/generated/numpy.nanprod.html#numpy.nanprod)(a[, axis, dtype, out, keepdims]) | Return the product of array elements over a given axis treating Not a Numbers (NaNs) as ones. |  
| [`nansum`](https://numpy.org/doc/stable/reference/generated/numpy.nansum.html#numpy.nansum)(a[, axis, dtype, out, keepdims]) | Return the sum of array elements over a given axis treating Not a Numbers (NaNs) as zero. |  
| [`cumprod`](https://numpy.org/doc/stable/reference/generated/numpy.cumprod.html#numpy.cumprod)(a[, axis, dtype, out]) | Return the cumulative product of elements along a given axis. |  
| [`cumsum`](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html#numpy.cumsum)(a[, axis, dtype, out]) | Return the cumulative sum of the elements along a given axis. |  
| [`nancumprod`](https://numpy.org/doc/stable/reference/generated/numpy.nancumprod.html#numpy.nancumprod)(a[, axis, dtype, out]) | Return the cumulative product of array elements over a given axis treating Not a Numbers (NaNs) as one. |  
| [`nancumsum`](https://numpy.org/doc/stable/reference/generated/numpy.nancumsum.html#numpy.nancumsum)(a[, axis, dtype, out]) | Return the cumulative sum of array elements over a given axis treating Not a Numbers (NaNs) as zero. |  
| [`diff`](https://numpy.org/doc/stable/reference/generated/numpy.diff.html#numpy.diff)(a[, n, axis, prepend, append]) | Calculate the n-th discrete difference along the given axis. |  
| [`ediff1d`](https://numpy.org/doc/stable/reference/generated/numpy.ediff1d.html#numpy.ediff1d)(ary[, to_end, to_begin]) | The differences between consecutive elements of an array.    |  
| [`gradient`](https://numpy.org/doc/stable/reference/generated/numpy.gradient.html#numpy.gradient)(f, *varargs[, axis, edge_order]) | Return the gradient of an N-dimensional array.               |  
| [`cross`](https://numpy.org/doc/stable/reference/generated/numpy.cross.html#numpy.cross)(a, b[, axisa, axisb, axisc, axis]) | Return the cross product of two (arrays of) vectors.         |  
| [`trapz`](https://numpy.org/doc/stable/reference/generated/numpy.trapz.html#numpy.trapz)(y[, x, dx, axis]) | Integrate along the given axis using the composite trapezoidal rule. |  

**Exponents and logarithms**  

| [`exp`](https://numpy.org/doc/stable/reference/generated/numpy.exp.html#numpy.exp)(x, /[, out, where, casting, order, …]) | Calculate the exponential of all elements in the input array. |  
| ------------------------------------------------------------ | ------------------------------------------------------------ |  
| [`expm1`](https://numpy.org/doc/stable/reference/generated/numpy.expm1.html#numpy.expm1)(x, /[, out, where, casting, order, …]) | Calculate `exp(x) - 1` for all elements in the array.        |  
| [`exp2`](https://numpy.org/doc/stable/reference/generated/numpy.exp2.html#numpy.exp2)(x, /[, out, where, casting, order, …]) | Calculate *2**p* for all *p* in the input array.             |  
| [`log`](https://numpy.org/doc/stable/reference/generated/numpy.log.html#numpy.log)(x, /[, out, where, casting, order, …]) | Natural logarithm, element-wise.                             |  
| [`log10`](https://numpy.org/doc/stable/reference/generated/numpy.log10.html#numpy.log10)(x, /[, out, where, casting, order, …]) | Return the base 10 logarithm of the input array, element-wise. |  
| [`log2`](https://numpy.org/doc/stable/reference/generated/numpy.log2.html#numpy.log2)(x, /[, out, where, casting, order, …]) | Base-2 logarithm of *x*.                                     |  
| [`log1p`](https://numpy.org/doc/stable/reference/generated/numpy.log1p.html#numpy.log1p)(x, /[, out, where, casting, order, …]) | Return the natural logarithm of one plus the input array, element-wise. |  
| [`logaddexp`](https://numpy.org/doc/stable/reference/generated/numpy.logaddexp.html#numpy.logaddexp)(x1, x2, /[, out, where, casting, …]) | Logarithm of the sum of exponentiations of the inputs.       |  
| [`logaddexp2`](https://numpy.org/doc/stable/reference/generated/numpy.logaddexp2.html#numpy.logaddexp2)(x1, x2, /[, out, where, casting, …]) | Logarithm of the sum of exponentiations of the inputs in base-2. |  

**Other special functions**  

| [`i0`](https://numpy.org/doc/stable/reference/generated/numpy.i0.html#numpy.i0)(x) | Modified Bessel function of the first kind, order 0. |  
| ------------------------------------------------------------ | ---------------------------------------------------- |  
| [`sinc`](https://numpy.org/doc/stable/reference/generated/numpy.sinc.html#numpy.sinc)(x) | Return the normalized sinc function.                 |  

**Floating point routines**  

| [`signbit`](https://numpy.org/doc/stable/reference/generated/numpy.signbit.html#numpy.signbit)(x, /[, out, where, casting, order, …]) | Returns element-wise True where signbit is set (less than zero). |  
| ------------------------------------------------------------ | ------------------------------------------------------------ |  
| [`copysign`](https://numpy.org/doc/stable/reference/generated/numpy.copysign.html#numpy.copysign)(x1, x2, /[, out, where, casting, …]) | Change the sign of x1 to that of x2, element-wise.           |  
| [`frexp`](https://numpy.org/doc/stable/reference/generated/numpy.frexp.html#numpy.frexp)(x[, out1, out2], / [[, out, where, …]) | Decompose the elements of x into mantissa and twos exponent. |  
| [`ldexp`](https://numpy.org/doc/stable/reference/generated/numpy.ldexp.html#numpy.ldexp)(x1, x2, /[, out, where, casting, …]) | Returns x1 * 2**x2, element-wise.                            |  
| [`nextafter`](https://numpy.org/doc/stable/reference/generated/numpy.nextafter.html#numpy.nextafter)(x1, x2, /[, out, where, casting, …]) | Return the next floating-point value after x1 towards x2, element-wise. |  
| [`spacing`](https://numpy.org/doc/stable/reference/generated/numpy.spacing.html#numpy.spacing)(x, /[, out, where, casting, order, …]) | Return the distance between x and the nearest adjacent number. |  

**Rational routines**  

| [`lcm`](https://numpy.org/doc/stable/reference/generated/numpy.lcm.html#numpy.lcm)(x1, x2, /[, out, where, casting, order, …]) | Returns the lowest common multiple of `|x1|` and `|x2|`  |  
| ------------------------------------------------------------ | -------------------------------------------------------- |  
| [`gcd`](https://numpy.org/doc/stable/reference/generated/numpy.gcd.html#numpy.gcd)(x1, x2, /[, out, where, casting, order, …]) | Returns the greatest common divisor of `|x1|` and `|x2|` |  

**Arithmetic operations**  

| [`add`](https://numpy.org/doc/stable/reference/generated/numpy.add.html#numpy.add)(x1, x2, /[, out, where, casting, order, …]) | Add arguments element-wise.                                  |  
| ------------------------------------------------------------ | ------------------------------------------------------------ |  
| [`reciprocal`](https://numpy.org/doc/stable/reference/generated/numpy.reciprocal.html#numpy.reciprocal)(x, /[, out, where, casting, …]) | Return the reciprocal of the argument, element-wise.         |  
| [`positive`](https://numpy.org/doc/stable/reference/generated/numpy.positive.html#numpy.positive)(x, /[, out, where, casting, order, …]) | Numerical positive, element-wise.                            |  
| [`negative`](https://numpy.org/doc/stable/reference/generated/numpy.negative.html#numpy.negative)(x, /[, out, where, casting, order, …]) | Numerical negative, element-wise.                            |  
| [`multiply`](https://numpy.org/doc/stable/reference/generated/numpy.multiply.html#numpy.multiply)(x1, x2, /[, out, where, casting, …]) | Multiply arguments element-wise.                             |  
| [`divide`](https://numpy.org/doc/stable/reference/generated/numpy.divide.html#numpy.divide)(x1, x2, /[, out, where, casting, …]) | Returns a true division of the inputs, element-wise.         |  
| [`power`](https://numpy.org/doc/stable/reference/generated/numpy.power.html#numpy.power)(x1, x2, /[, out, where, casting, …]) | First array elements raised to powers from second array, element-wise. |  
| [`subtract`](https://numpy.org/doc/stable/reference/generated/numpy.subtract.html#numpy.subtract)(x1, x2, /[, out, where, casting, …]) | Subtract arguments, element-wise.                            |  
| [`true_divide`](https://numpy.org/doc/stable/reference/generated/numpy.true_divide.html#numpy.true_divide)(x1, x2, /[, out, where, …]) | Returns a true division of the inputs, element-wise.         |  
| [`floor_divide`](https://numpy.org/doc/stable/reference/generated/numpy.floor_divide.html#numpy.floor_divide)(x1, x2, /[, out, where, …]) | Return the largest integer smaller or equal to the division of the inputs. |  
| [`float_power`](https://numpy.org/doc/stable/reference/generated/numpy.float_power.html#numpy.float_power)(x1, x2, /[, out, where, …]) | First array elements raised to powers from second array, element-wise. |  
| [`fmod`](https://numpy.org/doc/stable/reference/generated/numpy.fmod.html#numpy.fmod)(x1, x2, /[, out, where, casting, …]) | Return the element-wise remainder of division.               |  
| [`mod`](https://numpy.org/doc/stable/reference/generated/numpy.mod.html#numpy.mod)(x1, x2, /[, out, where, casting, order, …]) | Return element-wise remainder of division.                   |  
| [`modf`](https://numpy.org/doc/stable/reference/generated/numpy.modf.html#numpy.modf)(x[, out1, out2], / [[, out, where, …]) | Return the fractional and integral parts of an array, element-wise. |  
| [`remainder`](https://numpy.org/doc/stable/reference/generated/numpy.remainder.html#numpy.remainder)(x1, x2, /[, out, where, casting, …]) | Return element-wise remainder of division.                   |  
| [`divmod`](https://numpy.org/doc/stable/reference/generated/numpy.divmod.html#numpy.divmod)(x1, x2[, out1, out2], / [[, out, …]) | Return element-wise quotient and remainder simultaneously.   |  

**Handling complex numbers**  

| [`angle`](https://numpy.org/doc/stable/reference/generated/numpy.angle.html#numpy.angle)(z[, deg]) | Return the angle of the complex argument.          |  
| ------------------------------------------------------------ | -------------------------------------------------- |  
| [`real`](https://numpy.org/doc/stable/reference/generated/numpy.real.html#numpy.real)(val) | Return the real part of the complex argument.      |  
| [`imag`](https://numpy.org/doc/stable/reference/generated/numpy.imag.html#numpy.imag)(val) | Return the imaginary part of the complex argument. |  
| [`conj`](https://numpy.org/doc/stable/reference/generated/numpy.conj.html#numpy.conj)(x, /[, out, where, casting, order, …]) | Return the complex conjugate, element-wise.        |  
| [`conjugate`](https://numpy.org/doc/stable/reference/generated/numpy.conjugate.html#numpy.conjugate)(x, /[, out, where, casting, …]) | Return the complex conjugate, element-wise.        |  

**Miscellaneous**  

| [`convolve`](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html#numpy.convolve)(a, v[, mode]) | Returns the discrete, linear convolution of two one-dimensional sequences. |  
| ------------------------------------------------------------ | ------------------------------------------------------------ |  
| [`clip`](https://numpy.org/doc/stable/reference/generated/numpy.clip.html#numpy.clip)(a, a_min, a_max[, out]) | Clip (limit) the values in an array.                         |  
| [`sqrt`](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html#numpy.sqrt)(x, /[, out, where, casting, order, …]) | Return the non-negative square-root of an array, element-wise. |  
| [`cbrt`](https://numpy.org/doc/stable/reference/generated/numpy.cbrt.html#numpy.cbrt)(x, /[, out, where, casting, order, …]) | Return the cube-root of an array, element-wise.              |  
| [`square`](https://numpy.org/doc/stable/reference/generated/numpy.square.html#numpy.square)(x, /[, out, where, casting, order, …]) | Return the element-wise square of the input.                 |  
| [`absolute`](https://numpy.org/doc/stable/reference/generated/numpy.absolute.html#numpy.absolute)(x, /[, out, where, casting, order, …]) | Calculate the absolute value element-wise.                   |  
| [`fabs`](https://numpy.org/doc/stable/reference/generated/numpy.fabs.html#numpy.fabs)(x, /[, out, where, casting, order, …]) | Compute the absolute values element-wise.                    |  
| [`sign`](https://numpy.org/doc/stable/reference/generated/numpy.sign.html#numpy.sign)(x, /[, out, where, casting, order, …]) | Returns an element-wise indication of the sign of a number.  |  
| [`heaviside`](https://numpy.org/doc/stable/reference/generated/numpy.heaviside.html#numpy.heaviside)(x1, x2, /[, out, where, casting, …]) | Compute the Heaviside step function.                         |  
| [`maximum`](https://numpy.org/doc/stable/reference/generated/numpy.maximum.html#numpy.maximum)(x1, x2, /[, out, where, casting, …]) | Element-wise maximum of array elements.                      |  
| [`minimum`](https://numpy.org/doc/stable/reference/generated/numpy.minimum.html#numpy.minimum)(x1, x2, /[, out, where, casting, …]) | Element-wise minimum of array elements.                      |  
| [`fmax`](https://numpy.org/doc/stable/reference/generated/numpy.fmax.html#numpy.fmax)(x1, x2, /[, out, where, casting, …]) | Element-wise maximum of array elements.                      |  
| [`fmin`](https://numpy.org/doc/stable/reference/generated/numpy.fmin.html#numpy.fmin)(x1, x2, /[, out, where, casting, …]) | Element-wise minimum of array elements.                      |  
| [`nan_to_num`](https://numpy.org/doc/stable/reference/generated/numpy.nan_to_num.html#numpy.nan_to_num)(x[, copy, nan, posinf, neginf]) | Replace NaN with zero and infinity with large finite numbers (default behaviour) or with the numbers defined by the user using the [`nan`](https://numpy.org/doc/stable/reference/constants.html#numpy.nan), *posinf* and/or *neginf* keywords. |  
| [`real_if_close`](https://numpy.org/doc/stable/reference/generated/numpy.real_if_close.html#numpy.real_if_close)(a[, tol]) | If input is complex with all imaginary parts close to zero, return real parts. |  
| [`interp`](https://numpy.org/doc/stable/reference/generated/numpy.interp.html#numpy.interp)(x, xp, fp[, left, right, period]) | One-dimensional linear interpolation for monotonically increasing sample points. |

### Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape, as in the following example:

In [166]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. The simplest broadcasting example occurs when an array and a scalar value are combined in an operation:

In [167]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0

a * b

array([2., 4., 6.])

![](files/broadcasting_1.svg)

**General Broadcasting Rules**

Examples for broadcasting:  

```python  

Image  (3d array): 256 x 256 x 3  
Scale  (1d array):             3  
Result (3d array): 256 x 256 x 3  
    
    
A      (4d array):  8 x 1 x 6 x 1  
B      (3d array):      7 x 1 x 5  
Result (4d array):  8 x 7 x 6 x 5  

    
A      (2d array):  5 x 4  
B      (1d array):      1  
Result (2d array):  5 x 4  

    
A      (2d array):  5 x 4  
B      (1d array):      4  
Result (2d array):  5 x 4  

    
A      (3d array):  15 x 3 x 5  
B      (3d array):  15 x 1 x 5  
Result (3d array):  15 x 3 x 5  

    
A      (3d array):  15 x 3 x 5  
B      (2d array):       3 x 5  
Result (3d array):  15 x 3 x 5  

    
A      (3d array):  15 x 3 x 5  
B      (2d array):       3 x 1  
Result (3d array):  15 x 3 x 5  
```

![](files/broadcasting_2.svg)  


Examples of shapes that do not broadcast:  

```python  

A      (1d array):  3  
B      (1d array):  4 # trailing dimensions do not match  

A      (2d array):      2 x 1  
B      (3d array):  8 x 4 x 3 # second from last dimensions mismatched  


```

![](files/broadcasting_3.svg)  


# Matplotlib

`Matplotlib` is a plotting library. In this section give a brief introduction to the matplotlib.pyplot module, which provides a plotting system similar to that of MATLAB.

In [168]:
import matplotlib.pyplot as plt

## Plotting

The most important function in matplotlib is `plot`, which allows you to plot 2D data. Here is a simple example:

In [169]:
# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)
plt.show()  # You must call plt.show() to make graphics appear.

<Figure size 432x288 with 1 Axes>

With just a little bit of extra work we can easily plot multiple lines at once, and add a title, legend, and axis labels:

In [170]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()

<Figure size 432x288 with 1 Axes>

You can read much more about the plot function in the documentation.

## Subplots  

You can plot different things in the same figure using the `subplot` function. Here is an example:

In [171]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()

<Figure size 432x288 with 2 Axes>